# Generated by Django 5.2.15 on 2026-09-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0011_student_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='forms/', verbose_name='Imagen')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'formulario',
                'verbose_name_plural': 'formularios',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('answer_type', models.CharField(choices=[('yes_no', 'Sí o no'), ('short_text', 'Texto corto')], max_length=20, verbose_name='Tipo de respuesta')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoria')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='registration_forms.form', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'pregunta de formulario',
                'verbose_name_plural': 'preguntas de formulario',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='registration_forms.form', verbose_name='Formulario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='studio.student', verbose_name='Alumna')),
            ],
            options={
                'verbose_name': 'respuesta de formulario',
                'verbose_name_plural': 'respuestas de formulario',
                'ordering': ('-submitted_at',),
                'unique_together': {('form', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(blank=True, max_length=500, verbose_name='Texto')),
                ('yes_no', models.BooleanField(blank=True, null=True, verbose_name='Sí o no')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='registration_forms.formquestion', verbose_name='Pregunta')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='registration_forms.formsubmission', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'respuesta a pregunta',
                'verbose_name_plural': 'respuestas a preguntas',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
