# Generated by Django 5.2.15 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite'),
        ),
        migrations.AddField(
            model_name='form',
            name='allow_response_changes',
            field=models.BooleanField(default=False, verbose_name='Permitir cambiar la respuesta'),
        ),
    ]
