# Generated by Django 3.1.7 on 2021-04-03 09:25

import champs.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False, verbose_name='Publicado')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Fecha')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('location', models.CharField(default='', max_length=900, verbose_name='Localización')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Coste',
                'verbose_name_plural': 'Costes',
            },
        ),
        migrations.CreateModel(
            name='ChampFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Select file to upload', upload_to=champs.models.upload_champ_file, verbose_name='Fichero')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champs.championship', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Costo Campeonato',
                'verbose_name_plural': 'Costos Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='ChampCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Importe')),
                ('champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champs.championship', verbose_name='Campeonato')),
                ('cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='champs.cost', verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Costo Campeonato',
                'verbose_name_plural': 'Costos Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='ChampCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Importe')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='champs.category', verbose_name='Categoría')),
                ('champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champs.championship', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Categoría Campeonato',
                'verbose_name_plural': 'Categorías Campeonatos',
            },
        ),
    ]
