# Generated by Django 3.1.7 on 2021-05-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champfile',
            options={'verbose_name': 'Documento Campeonato', 'verbose_name_plural': 'Documentos Campeonatos'},
        ),
    ]
