# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 12:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True, verbose_name=b'Publicado')),
                ('code', models.CharField(max_length=10, verbose_name=b'C\xc3\xb3digo')),
                ('name', models.CharField(max_length=200, verbose_name=b'Nombre')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Costo')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Pvp')),
                ('stock', models.BigIntegerField(verbose_name=b'Stock')),
            ],
            options={
                'verbose_name': 'Art\xedculo',
                'verbose_name_plural': 'Art\xedculos',
            },
        ),
        migrations.CreateModel(
            name='ArticlePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name=b'Nota')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 425591), verbose_name=b'Fecha')),
                ('card', models.BooleanField(default=False, verbose_name=b'Tarjeta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Cantidad')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Article', verbose_name=b'Art\xc3\xadculo')),
            ],
            options={
                'verbose_name': 'Pago de art\xedculos',
                'verbose_name_plural': 'Pagos de art\xedculos',
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 428321), verbose_name=b'Fecha')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistenciass',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_card', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Tarjeta apertura')),
                ('e_card', models.IntegerField(blank=True, null=True, verbose_name=b'Tarjeta cierre')),
                ('i_50000', models.IntegerField(blank=True, null=True, verbose_name=b'500')),
                ('i_20000', models.IntegerField(blank=True, null=True, verbose_name=b'200')),
                ('i_10000', models.IntegerField(blank=True, null=True, verbose_name=b'100')),
                ('i_05000', models.IntegerField(blank=True, null=True, verbose_name=b'50')),
                ('i_02000', models.IntegerField(blank=True, null=True, verbose_name=b'20')),
                ('i_01000', models.IntegerField(blank=True, null=True, verbose_name=b'10')),
                ('i_00500', models.IntegerField(blank=True, null=True, verbose_name=b'5')),
                ('i_00200', models.IntegerField(blank=True, null=True, verbose_name=b'2')),
                ('i_00100', models.IntegerField(blank=True, null=True, verbose_name=b'1')),
                ('i_00050', models.IntegerField(blank=True, null=True, verbose_name=b'0,5')),
                ('i_00020', models.IntegerField(blank=True, null=True, verbose_name=b'0,2')),
                ('i_00010', models.IntegerField(blank=True, null=True, verbose_name=b'0,1')),
                ('i_00005', models.IntegerField(blank=True, null=True, verbose_name=b'0,05')),
                ('i_00002', models.IntegerField(blank=True, null=True, verbose_name=b'0,02')),
                ('i_00001', models.IntegerField(blank=True, null=True, verbose_name=b'0,01')),
                ('e_50000', models.IntegerField(blank=True, null=True, verbose_name=b'500')),
                ('e_20000', models.IntegerField(blank=True, null=True, verbose_name=b'200')),
                ('e_10000', models.IntegerField(blank=True, null=True, verbose_name=b'100')),
                ('e_05000', models.IntegerField(blank=True, null=True, verbose_name=b'50')),
                ('e_02000', models.IntegerField(blank=True, null=True, verbose_name=b'20')),
                ('e_01000', models.IntegerField(blank=True, null=True, verbose_name=b'10')),
                ('e_00500', models.IntegerField(blank=True, null=True, verbose_name=b'5')),
                ('e_00200', models.IntegerField(blank=True, null=True, verbose_name=b'2')),
                ('e_00100', models.IntegerField(blank=True, null=True, verbose_name=b'1')),
                ('e_00050', models.IntegerField(blank=True, null=True, verbose_name=b'0,5')),
                ('e_00020', models.IntegerField(blank=True, null=True, verbose_name=b'0,2')),
                ('e_00010', models.IntegerField(blank=True, null=True, verbose_name=b'0,1')),
                ('e_00005', models.IntegerField(blank=True, null=True, verbose_name=b'0,05')),
                ('e_00002', models.IntegerField(blank=True, null=True, verbose_name=b'0,02')),
                ('e_00001', models.IntegerField(blank=True, null=True, verbose_name=b'0,01')),
                ('i_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'Total apertura')),
                ('e_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'Total cierre')),
                ('i_note', models.CharField(blank=True, max_length=1000, verbose_name=b'Nota apertura')),
                ('e_note', models.CharField(blank=True, max_length=1000, verbose_name=b'Nota cierre')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 427031), verbose_name=b'Fecha')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name=b'C\xc3\xb3digo')),
                ('name', models.CharField(max_length=200, verbose_name=b'Nombre')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name=b'Activo')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 421819), verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('percent_studio', models.BigIntegerField(default=50, verbose_name=b'% Escuela')),
                ('percent_teacher', models.BigIntegerField(default=50, verbose_name=b'% Profesor')),
                ('price', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name=b'Precio')),
            ],
            options={
                'verbose_name': 'Matr\xedcula',
                'verbose_name_plural': 'Matr\xedculas',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name=b'Activo')),
                ('monday', models.BooleanField(default=False, verbose_name=b'Lunes')),
                ('tuesday', models.BooleanField(default=False, verbose_name=b'Martes')),
                ('wednesday', models.BooleanField(default=False, verbose_name=b'Mi\xc3\xa9rcoles')),
                ('thursday', models.BooleanField(default=False, verbose_name=b'Jueves')),
                ('friday', models.BooleanField(default=False, verbose_name=b'Viernes')),
                ('saturday', models.BooleanField(default=False, verbose_name=b'S\xc3\xa1bado')),
                ('sunday', models.BooleanField(default=False, verbose_name=b'Domingo')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 421015), verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('name', models.CharField(max_length=200, verbose_name=b'Nombre completo')),
                ('ini_time', models.TimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 421066), verbose_name=b'Fecha de inicio')),
                ('end_time', models.TimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 421090), verbose_name=b'Fecha de fin')),
            ],
            options={
                'ordering': ['teacher__name'],
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.BooleanField(default=False, verbose_name=b'Tarjeta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Cantidad')),
                ('note', models.CharField(max_length=200, verbose_name=b'Nota')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 423073), verbose_name=b'Fecha')),
                ('pay_date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 423098), verbose_name=b'Fecha de pago')),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 423120), verbose_name=b'Fecha de caducidad')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Enrolment', verbose_name=b'Matr\xc3\xadcula')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 420070), verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('born_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 21, 12, 15, 42, 420102), null=True, verbose_name=b'Fecha de nacimiento')),
                ('code', models.BigIntegerField(unique=True, verbose_name=b'C\xc3\xb3digo')),
                ('pin', models.CharField(default=studio.models.my_random_pin, max_length=4, unique=True, verbose_name=b'Pin')),
                ('name', models.CharField(max_length=200, verbose_name=b'Nombre completo')),
                ('phone', models.CharField(max_length=15, verbose_name=b'Tel\xc3\xa9fono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Correo electr\xc3\xb3nico')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name=b'Usuario')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name=b'Activo')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 418980), verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('code', models.BigIntegerField(verbose_name=b'C\xc3\xb3digo')),
                ('name', models.CharField(max_length=200, verbose_name=b'Nombre completo')),
                ('phone', models.CharField(max_length=15, verbose_name=b'Tel\xc3\xa9fono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Correo electr\xc3\xb3nico')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name=b'Usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name=b'Nota')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 15, 42, 423933), verbose_name=b'Fecha')),
                ('card', models.BooleanField(default=False, verbose_name=b'Tarjeta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Cantidad')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Concept', verbose_name=b'Concepto')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Teacher', verbose_name=b'Profesor')),
            ],
            options={
                'verbose_name': 'Pago a profesores',
                'verbose_name_plural': 'Pagos a profesores',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Student', verbose_name=b'Alumno'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Teacher', verbose_name=b'Profesor'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Group', verbose_name=b'Grupo'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Student', verbose_name=b'Alumno'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='enrolments',
            field=models.ManyToManyField(related_name='enrolemnts', to='studio.Enrolment'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Group', verbose_name=b'Group'),
        ),
        migrations.AddField(
            model_name='articlepayment',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Concept', verbose_name=b'Concepto'),
        ),
    ]
