# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, help_text=b'Seleccione una foto para subir', upload_to=studio.models.content_file_name, verbose_name=b'Foto'),
        ),
        migrations.AlterField(
            model_name='articlepayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(auto_now_add=True, verbose_name=b'Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ini_time',
            field=models.TimeField(auto_now_add=True, verbose_name=b'Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(verbose_name=b'Fecha'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.DateTimeField(verbose_name=b'Fecha de caducidad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateTimeField(verbose_name=b'Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='student',
            name='born_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Usuario'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Usuario'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha'),
        ),
    ]
