# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20160725_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Fecha de nacimiento'),
        ),
    ]
