# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20160725_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-pay_date'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(verbose_name=b'Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ini_time',
            field=models.TimeField(verbose_name=b'Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='date',
            field=models.DateTimeField(verbose_name=b'Fecha'),
        ),
    ]
