# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20160822_1321'),
        ('studio', '0004_auto_20160822_1329'),
    ]

    operations = [
    ]
