# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20160822_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name=b'Fecha'),
        ),
    ]
