# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20160823_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(verbose_name=b'Fecha'),
        ),
    ]
