# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_auto_20160823_1008'),
        ('studio', '0005_merge'),
    ]

    operations = [
    ]
