# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name=b'Fecha')),
                ('msg', models.TextField(default=b'', verbose_name=b'Mensaje')),
                ('students', models.ManyToManyField(blank=True, to='studio.Student', verbose_name=b'Alumnos')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
