# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment', to='studio.Student', verbose_name=b'Alumno'),
        ),
    ]
