# Generated by Django 3.1.7 on 2021-05-20 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0009_auto_20160913_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pvp'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.BigIntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='articlepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='articlepayment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.article', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='articlepayment',
            name='card',
            field=models.BooleanField(default=False, verbose_name='Tarjeta'),
        ),
        migrations.AlterField(
            model_name='articlepayment',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.concept', verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='articlepayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='articlepayment',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00001',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,01'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00002',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,02'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00005',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,05'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00010',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,1'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00020',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,2'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00050',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,5'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00100',
            field=models.IntegerField(blank=True, null=True, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00200',
            field=models.IntegerField(blank=True, null=True, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_00500',
            field=models.IntegerField(blank=True, null=True, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_01000',
            field=models.IntegerField(blank=True, null=True, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_02000',
            field=models.IntegerField(blank=True, null=True, verbose_name='20'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_05000',
            field=models.IntegerField(blank=True, null=True, verbose_name='50'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_10000',
            field=models.IntegerField(blank=True, null=True, verbose_name='100'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_20000',
            field=models.IntegerField(blank=True, null=True, verbose_name='200'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_50000',
            field=models.IntegerField(blank=True, null=True, verbose_name='500'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarjeta cierre'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_note',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Nota cierre'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='e_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total cierre'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00001',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,01'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00002',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,02'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00005',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,05'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00010',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,1'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00020',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,2'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00050',
            field=models.IntegerField(blank=True, null=True, verbose_name='0,5'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00100',
            field=models.IntegerField(blank=True, null=True, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00200',
            field=models.IntegerField(blank=True, null=True, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_00500',
            field=models.IntegerField(blank=True, null=True, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_01000',
            field=models.IntegerField(blank=True, null=True, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_02000',
            field=models.IntegerField(blank=True, null=True, verbose_name='20'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_05000',
            field=models.IntegerField(blank=True, null=True, verbose_name='50'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_10000',
            field=models.IntegerField(blank=True, null=True, verbose_name='100'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_20000',
            field=models.IntegerField(blank=True, null=True, verbose_name='200'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_50000',
            field=models.IntegerField(blank=True, null=True, verbose_name='500'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_card',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tarjeta apertura'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_note',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Nota apertura'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='i_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total apertura'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='percent_studio',
            field=models.BigIntegerField(default=50, verbose_name='% Escuela'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='percent_teacher',
            field=models.BigIntegerField(default=50, verbose_name='% Profesor'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment', to='studio.student', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='group',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Viernes'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ini_time',
            field=models.TimeField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='group',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Lunes'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='group',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Sábado'),
        ),
        migrations.AlterField(
            model_name='group',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.teacher', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Jueves'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Martes'),
        ),
        migrations.AlterField(
            model_name='group',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Miércoles'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='msg',
            field=models.TextField(default='', verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='students',
            field=models.ManyToManyField(blank=True, to='studio.Student', verbose_name='Alumnos'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card',
            field=models.BooleanField(default=False, verbose_name='Tarjeta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.enrolment', verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.DateTimeField(verbose_name='Fecha de caducidad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(max_length=200, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateTimeField(verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.student', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.BigIntegerField(unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='student',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, help_text='Seleccione una foto para subir', null=True, upload_to=studio.models.content_file_name, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pin',
            field=models.CharField(default=studio.models.my_random_pin, max_length=4, unique=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.BigIntegerField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='card',
            field=models.BooleanField(default=False, verbose_name='Tarjeta'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.concept', verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.teacher', verbose_name='Profesor'),
        ),
    ]
