# Generated by Django 3.1.7 on 2023-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_auto_20210520_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='band',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Pulsera'),
        ),
    ]
